'use client';

import { Download, UsersRound } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { DashboardShell } from '@/components/dashboard/shell';
import { opportunityService, type OpportunityInterestRegistration } from '@/lib/services/opportunity-service';

export default function InterestRegistrationsPage(): React.JSX.Element {
  const [items, setItems] = useState<OpportunityInterestRegistration[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState('');
  useEffect(() => { void opportunityService.interests().then(setItems).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => items.filter((item) => `${item.userId.name} ${item.userId.email} ${item.opportunityId.title}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  const download = () => { const rows = [['Member', 'Email', 'Phone', 'Opportunity', 'Opening capital', 'Monthly commitment', 'Readiness', 'Registered'], ...visible.map((item) => [item.userId.name, item.userId.email, item.userId.phone ?? '', item.opportunityId.title, String(item.openingCapital), String(item.recurringAmount ?? 0), label(item.capitalReadiness), new Date(item.createdAt).toLocaleString('en-NG')])]; const url = URL.createObjectURL(new Blob([rows.map((row) => row.map(csv).join(',')).join('\n')], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = 'playtives-interest-registrations.csv'; link.click(); URL.revokeObjectURL(url); };
  return <DashboardShell title="Interest Registrations" description="Members who have expressed interest in pre-launch opportunities."><div className="mx-auto max-w-6xl"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">Interest registrations</h1><p className="mt-2 text-sm text-muted-foreground">{items.length} total member expression{items.length === 1 ? '' : 's'} of interest.</p></div><button onClick={download} disabled={!visible.length} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold disabled:opacity-50"><Download className="size-4" />Export CSV</button></div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search member, email, or opportunity" className="mb-4 w-full max-w-md rounded-xl border bg-background px-4 py-2.5 text-sm outline-none focus:border-brand" />{loading ? <p className="p-10 text-center text-sm text-muted-foreground">Loading registrations…</p> : visible.length === 0 ? <div className="rounded-2xl border border-dashed p-10 text-center text-sm text-muted-foreground"><UsersRound className="mx-auto mb-3 size-7" />No matching interest registrations.</div> : <div className="overflow-x-auto rounded-2xl border bg-background"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b bg-muted/40 text-xs text-muted-foreground"><tr>{['Member', 'Opportunity', 'Opening capital', 'Monthly commitment', 'Readiness', 'Registered'].map((heading) => <th key={heading} className="px-4 py-3 font-semibold">{heading}</th>)}</tr></thead><tbody>{visible.map((item) => <tr key={item._id} className="border-b last:border-0"><td className="px-4 py-4"><p className="font-semibold">{item.userId.name}</p><p className="mt-1 text-xs text-muted-foreground">{item.userId.email}</p></td><td className="px-4 py-4 font-medium">{item.opportunityId.title}</td><td className="px-4 py-4">{money(item.openingCapital)}</td><td className="px-4 py-4">{money(item.recurringAmount ?? 0)}</td><td className="px-4 py-4">{label(item.capitalReadiness)}</td><td className="px-4 py-4 text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleString('en-NG')}</td></tr>)}</tbody></table></div>}</div></DashboardShell>;
}
function money(value: number): string { return new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 }).format(value); }
function label(value: OpportunityInterestRegistration['capitalReadiness']): string { return value === 'available_now' ? 'Available now' : value === 'within_7_days' ? 'Within 7 days' : 'Not sure yet'; }
function csv(value: string): string { return `"${value.replaceAll('"', '""')}"`; }
